const baseAutoComplite = [
  {
    name: "органические отходы",
    heat: 18.2,
    ashContent: 17.5,
    humidity: 77.2,
    massa: 23.63,
  },
  {
    name: "макулатура",
    heat: 16.9,
    ashContent: 15.3,
    humidity: 35.9,
    massa: 11.31,
  },
  {
    name: "полимеры",
    heat: 27.4,
    ashContent: 6.9,
    humidity: 25.6,
    massa: 16.71,
  },
  {
    name: "стекло",
    heat: 0,
    ashContent: 100,
    humidity: 3.5,
    massa: 7.65,
  },
  {
    name: "металлы",
    heat: 0,
    ashContent: 100,
    humidity: 3.5,
    massa: 1.4,
  },
  {
    name: "текстиль",
    heat: 22.6,
    ashContent: 5.2,
    humidity: 29.7,
    massa: 2.92,
  },
  {
    name: "дерево",
    heat: 18.9,
    ashContent: 4.9,
    humidity: 17.7,
    massa: 1.08,
  },
  {
    name: "комбинированные материалы",
    heat: 30,
    ashContent: 32.4,
    humidity: 11.9,
    massa: 1.67,
  },
  {
    name: "опасные материалы",
    heat: 20.1,
    ashContent: 50,
    humidity: 3.5,
    massa: 0.45,
  },
  {
    name: "инертные материалы",
    heat: 0,
    ashContent: 100,
    humidity: 7,
    massa: 4.95,
  },
  {
    name: "прочие материалы",
    heat: 30,
    ashContent: 27.3,
    humidity: 35.9,
    massa: 9.11,
  },
  {
    name: "отсев",
    heat: 20.1,
    ashContent: 55.8,
    humidity: 55.7,
    massa: 18.69,
  },
  {
    name: "прочее",
    heat: 20.1,
    ashContent: 0,
    humidity: 100,
  }
]