const baseAutoComplite = [
  {
    HeaderName: "Органические отходы",
    name: "пищевые отходы",
    massa: 21.6,
    humidity: 78.6,
    ashContent: 62.4,
    heat: 18.2,
  },
  {
    HeaderName: "Органические отходы",
    name: "растительные отходы",
    massa: 2,
    humidity: 62.4,
    ashContent: 19.6,
    heat: 18.7,
  },
  {
    HeaderName: "Полимеры",
    name: "пленка полиэтиленовая",
    massa: 7,
    humidity: 42.9,
    ashContent: 10.8,
    heat: 27.4,
  },
  {
    HeaderName: "Полимеры",
    name: "пленка полипропиленовая",
    massa: 1.1,
    humidity: 33.6,
    ashContent: 3.6,
    heat: 45,
  },
  {
    HeaderName: "Полимеры",
    name: "металлиз. и многослойная пленка",
    massa: 1,
    humidity: 20.8,
    ashContent: 7.2,
    heat: 27.4,
  },
  {
    HeaderName: "Полимеры",
    name: "пэт-бутылка прозрачная",
    massa: 1.5,
    humidity: 4.6,
    ashContent: 0.5,
    heat: 21,
  },
  {
    HeaderName: "Полимеры",
    name: "пэт-бутылка зеленая",
    massa: 0.2,
    humidity: 4.6,
    ashContent: 0.5,
    heat: 21,
  },
  {
    HeaderName: "Полимеры",
    name: "пэт-бутылка синяя",
    massa: 0.1,
    humidity: 4.6,
    ashContent: 0.5,
    heat: 21,
  },
  {
    HeaderName: "Полимеры",
    name: "пэт-бутылка темная",
    massa: 0.3,
    humidity: 4.6,
    ashContent: 0.5,
    heat: 21,
  },
  {
    HeaderName: "Полимеры",
    name: "пэ-бутылки",
    massa: 0.9,
    humidity: 2.4,
    ashContent: 3,
    heat: 27.4,
  },
  {
    HeaderName: "Полимеры",
    name: "полимерная упаковка",
    massa: 1.9,
    humidity: 18.5,
    ashContent: 3.3,
    heat: 27.4,
  },
  {
    HeaderName: "Полимеры",
    name: "прочие полимеры",
    massa: 2.7,
    humidity: 8.2,
    ashContent: 6.9,
    heat: 27.4,
  },
  {
    HeaderName: "Макулатура",
    name: "картон крупный",
    massa: 1.5,
    humidity: 28.7,
    ashContent: 10.6,
    heat: 16.9,
  },
  {
    HeaderName: "Макулатура",
    name: "картон мелкий",
    massa: 2.5,
    humidity: 28.4,
    ashContent: 12.3,
    heat: 16.9,
  },
  {
    HeaderName: "Макулатура",
    name: "офисная бумага",
    massa: 0.8,
    humidity: 23.2,
    ashContent: 20.4,
    heat: 16.9,
  },
  {
    HeaderName: "Макулатура",
    name: "газетная бумага",
    massa: 1.1,
    humidity: 38.7,
    ashContent: 7.1,
    heat: 16.9,
  },
  {
    HeaderName: "Макулатура",
    name: "книги и тетрадки в обложке",
    massa: 0.3,
    humidity: 15.2,
    ashContent: 20.3,
    heat: 16.9,
  },
  {
    HeaderName: "Макулатура",
    name: "глянцевая бумага",
    massa: 0.5,
    humidity: 17.6,
    ashContent: 36.2,
    heat: 16.9,
  },
  {
    HeaderName: "Макулатура",
    name: "прочая макулатура",
    massa: 4.6,
    humidity: 47.1,
    ashContent: 16.9,
    heat: 16.9,
  },

  {
    HeaderName: "Дерево",
    name: "дерево",
    massa: 1.1,
    humidity: 18,
    ashContent: 5,
    heat: 18.9,
  },

  {
    HeaderName: "Текстиль",
    name: "одежда",
    massa: 1.5,
    humidity: 27.6,
    ashContent: 4.9,
    heat: 22.6,
  },
  {
    HeaderName: "Текстиль",
    name: "прочий текcтиль",
    massa: 1.4,
    humidity: 32.1,
    ashContent: 5.6,
    heat: 22.6,
  },
  {
    HeaderName: "Комбинированные материалы",
    name: "комбинированная упаковка (тетрапак)",
    massa: 0.8,
    humidity: 21.7,
    ashContent: 11.7,
    heat: 30,
  },
  {
    HeaderName: "Комбинированные материалы",
    name: "электронные отходы",
    massa: 0.3,
    humidity: 3.5,
    ashContent: 50,
    heat: 33,
  },
  {
    HeaderName: "Комбинированные материалы",
    name: "прочие комбинированные материалы",
    massa: 0.6,
    humidity: 3.5,
    ashContent: 50,
    heat: 20.1,
  },

  {
    HeaderName: "Металлы",
    name: "черный металл",
    massa: 0.2,
    humidity: 3.5,
    ashContent: 100,
    heat: 0,
  },
  {
    HeaderName: "Металлы",
    name: "жестяная банка",
    massa: 0.8,
    humidity: 3.5,
    ashContent: 100,
    heat: 0,
  },
  {
    HeaderName: "Металлы",
    name: "цветной металл",
    massa: 0.2,
    humidity: 3.5,
    ashContent: 100,
    heat: 0,
  },
  {
    HeaderName: "Металлы",
    name: "алюминиевая банка",
    massa: 0.2,
    humidity: 3.5,
    ashContent: 100,
    heat: 0,
  },

  {
    HeaderName: "Стекло",
    name: "стеклотара прозрачная",
    massa: 3.8,
    humidity: 3.5,
    ashContent: 100,
    heat: 0,
  },
  {
    HeaderName: "Стекло",
    name: "стеклотара зеленая и синяя",
    massa: 1.5,
    humidity: 3.5,
    ashContent: 100,
    heat: 0,
  },
  {
    HeaderName: "Стекло",
    name: "стеклотара темная",
    massa: 1.2,
    humidity: 3.5,
    ashContent: 100,
    heat: 0,
  },
  {
    HeaderName: "Стекло",
    name: "прочее стекло",
    massa: 1.3,
    humidity: 3.5,
    ashContent: 100,
    heat: 0,
  },
  {
    HeaderName: "Опасные материалы",
    name: "опасные материалы",
    massa: 0.5,
    humidity: 3.5,
    ashContent: 50,
    heat: 20.1,
  },
  {
    HeaderName: "Инертные материалы",
    name: "строительные отходы",
    massa: 1.9,
    humidity: 4.4,
    ashContent: 100,
    heat: 0,
  },
  {
    HeaderName: "Инертные материалы",
    name: "прочие инертные материалы",
    massa: 3,
    humidity: 8.7,
    ashContent: 100,
    heat: 0,
  },
  {
    HeaderName: "Отсев",
    name: "отсев",
    massa: 18.7,
    humidity: 55.7,
    ashContent: 55.7,
    heat: 20.1,
  },

  {
    HeaderName: "Прочие материалы",
    name: "кожа, резина, обувь",
    massa: 0.8,
    humidity: 10.8,
    ashContent: 22.1,
    heat: 30,
  },
  {
    HeaderName: "Прочие материалы",
    name: "подгузники одноразовые",
    massa: 4.7,
    humidity: 65.4,
    ashContent: 10.6,
    heat: 20.6,
  },
  {
    HeaderName: "Прочие материалы",
    name: "прочее",
    massa: 3.6,
    humidity: 100,
    ashContent: 0,
    heat: 20.1,
  },
  {
    name: "жидкость(вода)",
    humidity: 100,
    ashContent: 0,
    heat: 0,
  },
];



